### ISSUE TITLE
Add minimum modifier option

### ISSUE THREAD

**Issue by ilore** [Nordiii/difficultterrain#10]
When you make a square with your mouse, the module creates a x2 modifier area. This is great but sometimes you will need to create a modifier area higher than x2. Adding a minimum modifier option could help to do this.

**Comment by Nordiii** [comment]
@ilore could you please elaborate this? When you are using only my module you can set the max modifier in the module settings.

If you are using [Terrain Layer](https://github.com/wsaunders1014/TerrainLayer))) to mark difficult terrain, then you should open an issue there, but I seem to remember that WSaunders said (on discord) that he is going to take a break.

But you can add x3 difficulty by double clicking the same square.

**Comment by ilore** [comment]
Oh! Yes, I was trying to write WSaunders, I´m new using github, sorry! Thank you for your quick response! You can eliminate this request if you want.
